create table if not exists public.saved_agents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  repo_url text not null,
  repo_name text not null,
  score integer,
  verdict text,
  created_at timestamptz not null default now(),
  unique(user_id, repo_url)
);

create table if not exists public.scan_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  repo_url text not null,
  repo_name text not null,
  score integer,
  verdict text,
  created_at timestamptz not null default now()
);

alter table public.saved_agents enable row level security;
alter table public.scan_history enable row level security;

create policy "users read own saved agents" on public.saved_agents for select using (auth.uid()=user_id);
create policy "users write own saved agents" on public.saved_agents for insert with check (auth.uid()=user_id);
create policy "users update own saved agents" on public.saved_agents for update using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "users delete own saved agents" on public.saved_agents for delete using (auth.uid()=user_id);
create policy "users read own history" on public.scan_history for select using (auth.uid()=user_id);
create policy "users write own history" on public.scan_history for insert with check (auth.uid()=user_id);
