import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const MAX_FILE = 80_000;
const MAX_FILES = 32;
const CACHE_MS = 5 * 60_000;
const RATE_WINDOW_MS = 60_000;
const RATE_LIMIT = 30;
const searchCache = new Map<string, { at: number; data: unknown }>();
const analysisCache = new Map<string, { at: number; data: unknown }>();
const rateHits = new Map<string, { at: number; count: number }>();
const ALLOWED_ORIGINS = new Set(['https://paradox.engineer','http://localhost:4321','http://127.0.0.1:4321']);
const SOURCE_EXT = /\.(?:ts|tsx|js|jsx|mjs|cjs|py|java|kt|go|rs|php|cs|rb|swift|sh|yml|yaml)$/i;
const SKIP_PATH = /(?:^|\/)(?:node_modules|\.git|dist|build|coverage|vendor|target|\.next|\.astro)(?:\/|$)/i;
const INTERESTING = ['README.md','readme.md','README','package.json','requirements.txt','pyproject.toml','Cargo.toml','go.mod','pom.xml','build.gradle','build.gradle.kts','Dockerfile','docker-compose.yml','docker-compose.yaml','.env.example','compose.yml'];
function cors(req: Request) { const origin=req.headers.get('origin')||''; return {'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(origin)?origin:'https://paradox.engineer','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'}; }
function json(data:unknown,status:number,h:Record<string,string>,cache=0){return new Response(JSON.stringify(data),{status,headers:{...h,'Content-Type':'application/json','Cache-Control':cache?`public,max-age=${Math.floor(cache/1000)}`:'no-store'}})}
function requestKey(req:Request){return req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||req.headers.get('cf-connecting-ip')||'unknown'}
function allowed(req:Request){const key=requestKey(req);const now=Date.now();const row=rateHits.get(key);if(!row||now-row.at>RATE_WINDOW_MS){rateHits.set(key,{at:now,count:1});return true}row.count+=1;return row.count<=RATE_LIMIT}
function parseRepo(raw:string){const v=raw.trim();const url=new URL(v.includes('://')?v:`https://${v}`);if(!['github.com','www.github.com'].includes(url.hostname.toLowerCase()))throw new Error('github-host');const p=url.pathname.split('/').filter(Boolean);if(p.length<2)throw new Error('github-repo');const owner=p[0],repo=p[1].replace(/\.git$/i,'');if(!/^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$/.test(owner)||!/^[A-Za-z0-9._-]{1,100}$/.test(repo)||owner==='.'||owner==='..'||repo==='.'||repo==='..')throw new Error('github-repo');return{owner,repo,fullName:`${owner}/${repo}`}}
const token=Deno.env.get('GITHUB_TOKEN')||'';const ghHeaders:Record<string,string>={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(token)ghHeaders.Authorization=`Bearer ${token}`;
async function gh(path:string){const r=await fetch(`https://api.github.com${path}`,{headers:ghHeaders});const data=await r.json().catch(()=>null);return{status:r.status,ok:r.ok,data}}
function encodePath(path:string){return path.split('/').map(encodeURIComponent).join('/')}
function decodeBase64(v:string){try{const bytes=Uint8Array.from(atob(v.replace(/\s/g,'')),c=>c.charCodeAt(0));return new TextDecoder().decode(bytes).slice(0,MAX_FILE)}catch{return ''}}
async function readFile(owner:string,repo:string,path:string){const r=await gh(`/repos/${owner}/${repo}/contents/${encodePath(path)}`);if(!r.ok||!r.data||r.data.type!=='file')return null;const size=Number(r.data.size||0);if(size>MAX_FILE)return{path,content:'',size,skipped:true};return{path,content:typeof r.data.content==='string'?decodeBase64(r.data.content):'',size,skipped:false}}
function selectPaths(rootNames:string[],treeItems:Array<{path?:string;type?:string;size?:number}>){const available=new Set(treeItems.filter(x=>x.type==='blob'&&x.path&&!SKIP_PATH.test(x.path)).map(x=>x.path as string));const priority=INTERESTING.filter(n=>rootNames.some(x=>x.toLowerCase()===n.toLowerCase())).concat(treeItems.filter(x=>x.type==='blob'&&x.path&&!SKIP_PATH.test(x.path)&&/\.github\/workflows\//i.test(x.path)).map(x=>x.path as string));const source=treeItems.filter(x=>x.type==='blob'&&x.path&&!SKIP_PATH.test(x.path)&&SOURCE_EXT.test(x.path)&&Number(x.size||0)<=MAX_FILE).sort((a,b)=>String(a.path).length-String(b.path).length).map(x=>x.path as string);return[...new Set([...priority.filter(x=>available.has(x)),...source])].slice(0,MAX_FILES)}
async function analyze(owner:string,repo:string){const key=`${owner}/${repo}`.toLowerCase();const hit=analysisCache.get(key);if(hit&&Date.now()-hit.at<CACHE_MS)return hit.data;const rr=await gh(`/repos/${owner}/${repo}`);if(rr.status===404)throw new ResponseError('GitHub could not find this public repository.',404);if(rr.status===403)throw new ResponseError('GitHub is temporarily rate limiting requests. Please try again shortly.',429);if(!rr.ok||!rr.data||rr.data.private)throw new ResponseError('This repository is not publicly accessible.',404);const branch=String(rr.data.default_branch||'main');const[languages,root,contributors,releases,commits,tree]=await Promise.all([gh(`/repos/${owner}/${repo}/languages`),gh(`/repos/${owner}/${repo}/contents`),gh(`/repos/${owner}/${repo}/contributors?per_page=100&anon=true`),gh(`/repos/${owner}/${repo}/releases?per_page=1`),gh(`/repos/${owner}/${repo}/commits?per_page=1`),gh(`/repos/${owner}/${repo}/git/trees/${encodeURIComponent(branch)}?recursive=1`)]);const rootItems=Array.isArray(root.data)?root.data:[];const names=rootItems.map((x:{name?:string})=>String(x.name||''));const treeItems=tree.ok&&Array.isArray(tree.data?.tree)?tree.data.tree:[];const paths=selectPaths(names,treeItems);const files=(await Promise.all(paths.map(p=>readFile(owner,repo,p)))).filter(Boolean);const data={repo:rr.data,languages:languages.ok?languages.data:{},root:rootItems.slice(0,100),files,contributors:Array.isArray(contributors.data)?Math.min(contributors.data.length,100):null,latestRelease:Array.isArray(releases.data)?releases.data[0]?.tag_name||null:null,latestCommit:Array.isArray(commits.data)?commits.data[0]?.commit?.committer?.date||null:null,analyzedAt:new Date().toISOString(),method:'static-analysis',coverage:{selectedFiles:files.length,maxFiles:MAX_FILES,recursiveTree:tree.ok&&!tree.data?.truncated}};analysisCache.set(key,{at:Date.now(),data});return data}
async function search(query:string){const q=query.trim().slice(0,120)||'ai agent';const key=q.toLowerCase();const hit=searchCache.get(key);if(hit&&Date.now()-hit.at<CACHE_MS)return hit.data;const r=await gh(`/search/repositories?q=${encodeURIComponent(q)}&sort=updated&order=desc&per_page=20`);if(r.status===403)throw new ResponseError('GitHub is temporarily rate limiting requests. Please try again shortly.',429);if(!r.ok)throw new ResponseError("We couldn't complete this search. Try again.",502);const data={total_count:Number(r.data?.total_count||0),items:Array.isArray(r.data?.items)?r.data.items:[]};searchCache.set(key,{at:Date.now(),data});return data}
class ResponseError extends Error{status:number;constructor(message:string,status:number){super(message);this.status=status}}
Deno.serve(async(req)=>{const h=cors(req);if(req.method==='OPTIONS')return new Response('ok',{headers:h});if(req.method!=='POST')return json({error:'Method not allowed'},405,h);if(!allowed(req))return json({error:'Too many analysis requests. Please wait a minute.'},429,h);try{const body=await req.json();if(body.mode==='search')return json(await search(String(body.query||'')),200,h,20_000);const ref=parseRepo(String(body.url||''));return json(await analyze(ref.owner,ref.repo),200,h,60_000)}catch(e){if(e instanceof ResponseError)return json({error:e.message},e.status,h);const message=e instanceof Error&&['github-host','github-repo'].includes(e.message)?'Enter a public GitHub repository URL.':"We couldn't complete this request. Try again.";return json({error:message},400,h)}});
