const modal=document.getElementById('modal'),game=document.getElementById('game');
const suits=[['♠','Black'],['♥','Red'],['♣','Black'],['♦','Red']];
const target=['♠','♥','♣','♦'][Math.floor(Math.random()*4)];
let path=[];
function startTrick(){path=[];modal.classList.add('open');modal.setAttribute('aria-hidden','false');renderStart()}
function closeTrick(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function renderStart(){game.innerHTML='<div class="game"><div class="game-top">PARADOX / SEALED PREDICTION</div><h2>There is a card in the envelope.</h2><p>Before we begin, I have committed to one suit. You won’t see it yet.</p><p>Now choose the suit that feels right. Don’t choose the one you think I want.</p><div class="cards">'+suits.map((s,i)=>'<button class="playing" onclick="firstChoice('+i+')"><span class="mark">'+s[0]+'</span><small>'+s[1]+' suit</small></button>').join('')+'</div></div>'}
function firstChoice(i){path.push(suits[i][0]);renderSplit(suits.map((s,j)=>j===i?'<b>YOUR PICK</b>':'').join(''))}
function renderSplit(){const others=suits.map((s,i)=>'<button class="choice" onclick="secondChoice('+i+')">'+s[0]+' '+s[1]+'</button>').join('');game.innerHTML='<div class="game"><div class="game-top">DECISION 02</div><h2>Good. Now make it harder.</h2><p>Your first choice is locked. Of the four suits, choose <b>two to remove from the table</b>. Do it quickly.</p><div class="choice">'+suits.map((s,i)=>'<button onclick="removeChoice('+i+',this)">'+s[0]+' · remove</button>').join('')+'</div><div id="status"></div></div>'}
let removed=[];
function removeChoice(i,el){if(removed.includes(i))return;removed.push(i);el.disabled=true;el.style.opacity=.35;document.getElementById('status').innerHTML='<div class="locked"><b>'+removed.length+'/2 LOCKED</b><br>'+removed.map(x=>suits[x][0]).join('  ·  ')+'</div>';if(removed.length===2)setTimeout(()=>finalChoice(),350)}
function finalChoice(){let remain=suits.map((s,i)=>i).filter(i=>!removed.includes(i));game.innerHTML='<div class="game"><div class="game-top">LAST DECISION</div><h2>One last cut.</h2><p>Two suits remain. You can keep either one. Tap the one you want to survive.</p><div class="choice">'+remain.map(i=>'<button onclick="finish('+i+')">'+suits[i][0]+' '+suits[i][1]+'</button>').join('')+'</div></div>'}
function finish(i){path.push(suits[i][0]);reveal()}
function reveal(){game.innerHTML='<div class="game"><div class="game-top">THE REVEAL</div><h2>Open it.</h2><p>You made the choices. I won’t touch the prediction now.</p><div class="envelope" onclick="openEnvelope()"><div class="seal">OPEN</div></div><p style="text-align:center;font:11px DM Mono;color:#777">Tap the seal</p></div>'}
function openEnvelope(){game.innerHTML='<div class="game"><div class="game-top">THE REVEAL</div><h2>That was your card.</h2><div class="reveal"><h3>'+target+' · The sealed prediction.</h3><p>You chose '+path.join(' → ')+'. The prediction was committed before you saw it.</p></div><details class="method"><summary>Okay. How did you do that?</summary><p>This is a classic magician’s principle called <b>equivoque</b> (the magician’s choice). The trick is not that the browser reads your mind. The wording and the structure of the choices let the performer steer which object survives while making every individual action feel like your own decision.</p><p>That’s the important part: the illusion lives in <i>how a choice feels</i>, not in pretending there is supernatural intelligence behind it.</p></details><button class="again" onclick="startTrick()">Try to beat it</button></div>'}
