const startStudio=()=>{const root=document.querySelector<HTMLElement>('#studioPage,.studio');if(!root||root.dataset.studioUiReady==='true')return;root.dataset.studioUiReady='true';
const tabs=[...root.querySelectorAll<HTMLButtonElement>('[data-section-tab]')];
const panels={workflows:root.querySelector<HTMLElement>('#studioWorkflows'),toolkit:root.querySelector<HTMLElement>('#studioToolkit'),radar:root.querySelector<HTMLElement>('#studioRadar')};
const setSection=(section:'workflows'|'toolkit'|'radar',writeUrl=true)=>{
 tabs.forEach(tab=>{const active=tab.dataset.sectionTab===section;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));});
 (Object.entries(panels) as Array<[keyof typeof panels,HTMLElement|null]>).forEach(([key,panel])=>{if(panel)panel.hidden=key!==section;});
 if(writeUrl){const u=new URL(location.href);u.searchParams.delete('section');u.searchParams.delete('workflow');u.searchParams.delete('tool');if(section==='toolkit'){u.searchParams.set('section','toolkit');const active=root.querySelector<HTMLElement>('.tool-item.active,.studio-tool-select.active');if(active?.dataset.toolSelect)u.searchParams.set('tool',active.dataset.toolSelect);}else if(section==='radar')u.searchParams.set('section','radar');else u.searchParams.set('workflow','resume');history.replaceState(null,'',u.pathname+u.search);}
 if(section==='radar')void loadRadar();
};
const chooseTool=(button:HTMLElement)=>{root.querySelectorAll<HTMLElement>('.tool-item,.studio-tool-select').forEach(item=>item.classList.toggle('active',item===button));setSection('toolkit',false);window.dispatchEvent(new CustomEvent('paradox:ai-tool-change',{detail:{mode:button.dataset.toolMode||'',title:button.querySelector('strong,span strong')?.textContent?.trim()||'Developer Tool',intro:button.querySelector('small')?.textContent?.trim()||''}}));const u=new URL(location.href);u.searchParams.set('section','toolkit');if(button.dataset.toolSelect)u.searchParams.set('tool',button.dataset.toolSelect);history.replaceState(null,'',u.pathname+u.search);};
tabs.forEach(tab=>tab.addEventListener('click',()=>{const section=(tab.dataset.sectionTab||'workflows') as 'workflows'|'toolkit'|'radar';if(section==='toolkit'){const active=root.querySelector<HTMLElement>('.tool-item.active,.studio-tool-select.active')||root.querySelector<HTMLElement>('.tool-item,.studio-tool-select');if(active)chooseTool(active);else setSection('toolkit');}else setSection(section);}));
root.querySelectorAll<HTMLButtonElement>('.workflow-item,.flow').forEach(button=>button.addEventListener('click',()=>{const flow=button.dataset.flow||'resume';root.querySelectorAll<HTMLElement>('.workflow-item,.flow').forEach(item=>item.classList.toggle('active',item===button));setSection('workflows',false);const u=new URL(location.href);u.searchParams.set('workflow',flow);u.searchParams.delete('section');u.searchParams.delete('tool');history.replaceState(null,'',u.pathname+u.search);window.dispatchEvent(new CustomEvent('paradox:workflow-change',{detail:{flow}}));}));
root.querySelectorAll<HTMLButtonElement>('.tool-item,.studio-tool-select').forEach(button=>button.addEventListener('click',()=>chooseTool(button)));
const search=root.querySelector<HTMLInputElement>('#toolSearch');search?.addEventListener('input',()=>{const q=search.value.trim().toLowerCase();root.querySelectorAll<HTMLElement>('.tool-item,.studio-tool-select').forEach(item=>item.hidden=Boolean(q&&!item.textContent?.toLowerCase().includes(q)));});
let radarLoaded=false;
async function loadRadar(){if(radarLoaded)return;const studioRoot=root;const models=studioRoot.querySelector<HTMLElement>('#radarModels'),github=root.querySelector<HTMLElement>('#radarGithub'),news=root.querySelector<HTMLElement>('#radarNews'),status=root.querySelector<HTMLElement>('#radarStatus');if(!models||!github||!news||!status)return;radarLoaded=true;status.textContent='FETCHING…';const fetchJson=async(url:string)=>{const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),10000);try{const response=await fetch(url,{signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error('request failed');return await response.json()}finally{window.clearTimeout(timer)}};const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));const results=await Promise.allSettled([fetchJson('https://huggingface.co/api/models?sort=trending&direction=-1&limit=8'),fetchJson('https://api.github.com/search/repositories?q=AI+OR+LLM&sort=stars&order=desc&per_page=8'),fetchJson('https://hn.algolia.com/api/v1/search?query=AI%20LLM&tags=story&hitsPerPage=8')]);const modelsData=results[0].status==='fulfilled'?results[0].value:[],repos=results[1].status==='fulfilled'?(results[1].value.items||[]):[],stories=results[2].status==='fulfilled'?(results[2].value.hits||[]):[];models.innerHTML=modelsData.length?modelsData.map((item:any,i:number)=>'<a class="studio-radar-card" href="https://huggingface.co/'+esc(item.id)+'" target="_blank" rel="noreferrer"><strong>'+String(i+1).padStart(2,'0')+' · '+esc(item.id)+'</strong><span>'+Number(item.downloads||0).toLocaleString()+' downloads · '+Number(item.likes||0).toLocaleString()+' likes</span></a>').join(''):'<p class="radar-empty">Model feed unavailable right now.</p>';github.innerHTML=repos.length?repos.map((item:any)=>'<a class="studio-radar-card" href="'+esc(item.html_url)+'" target="_blank" rel="noreferrer"><strong>'+esc(item.name)+'</strong><span>★ '+Number(item.stargazers_count||0).toLocaleString()+'</span></a>').join(''):'<p class="radar-empty">GitHub feed unavailable right now.</p>';news.innerHTML=stories.length?stories.map((item:any)=>'<a class="studio-radar-card" href="'+esc(item.url||'https://news.ycombinator.com/')+'" target="_blank" rel="noreferrer"><strong>'+esc(item.title||'AI story')+'</strong><span>'+Number(item.points||0)+' points · '+Number(item.num_comments||0)+' comments</span></a>').join(''):'<p class="radar-empty">News feed unavailable right now.</p>';status.textContent=`${[modelsData,repos,stories].filter(items=>items.length).length}/3 LIVE`;}
const params=new URLSearchParams(location.search);const requested=params.get('section');if(requested==='radar')setSection('radar',false);else if(requested==='toolkit'){const slug=params.get('tool');const selector=slug?`.tool-item[data-tool-select="${CSS.escape(slug)}"],.studio-tool-select[data-tool-select="${CSS.escape(slug)}"]` : '.tool-item,.studio-tool-select';const match=root.querySelector<HTMLElement>(selector);if(match)chooseTool(match);else setSection('toolkit',false);}else setSection('workflows',false);};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startStudio,{once:true});else startStudio();
export {};