import { currentUser, supabase } from '../lib/supabase.ts';

type Provider='auto'|'gemini'|'groq'|'cerebras'|'huggingface'|'ollama';
type Field=[string,string,'text'|'ta',string,string?];
const workflows:Record<string,{label:string;title:string;fields:Field[]}>={
 resume:{label:'RESUME TAILOR',title:'Make the application fit.',fields:[['Your resume','resume','ta','Paste your resume here...'],['Job description','jd','ta','Paste the job description here...'],['Target role','role','text','Software Engineer']]},
 interview:{label:'INTERVIEW COACH',title:'Train against the actual role.',fields:[['Job description','jd','ta','Paste the job description here...'],['Your background','bg','ta','Projects, experience, skills, education...'],['Interview stage','stage','text','Technical interview']]},
 study:{label:'STUDY ENGINE',title:'Turn notes into a revision system.',fields:[['Topic or chapter','topic','text','DBMS — normalization'],['Notes / source material','notes','ta','Paste class notes, textbook text or your own notes...'],['Difficulty','difficulty','text','University exam']]},
 content:{label:'CONTENT STUDIO',title:'Go from idea to publishable draft.',fields:[['Idea / brief','brief','ta','What are you trying to say?'],['Audience','audience','text','College students and young professionals'],['Format','format','text','LinkedIn post']]},
 code:{label:'CODE FIXER',title:'Understand the bug before you patch it.',fields:[['Code','code','ta','Paste the code that is failing...'],['Error / expected behaviour','errorInfo','ta','Paste the error or explain what should happen.'],['Language','language','text','JavaScript']]}
};
const samples:Record<string,Record<string,string>>={
 resume:{resume:'Software engineering student. Built React + Node.js applications, REST APIs and PostgreSQL-backed projects.',jd:'Software Engineer\nBuild REST APIs, React interfaces, Git and database-backed products.',role:'Software Engineer'},
 interview:{jd:'Software Engineer\nReact, JavaScript, REST APIs, PostgreSQL, Git.',bg:'Computer Science student. Full-stack projects using React, Node.js, Express, PostgreSQL and MongoDB.',stage:'Technical interview'},
 study:{topic:'Database Management Systems — normalization',notes:'1NF requires atomic values. 2NF removes partial dependency. 3NF removes transitive dependency.',difficulty:'University exam'},
 content:{brief:'Launch announcement for a developer platform combining AI workflows and browser utilities.',audience:'Developers and students',format:'LinkedIn post'},
 code:{code:'const users = [1, 2, 3];\nconsole.log(users.map(user => user.name));',errorInfo:'The output is undefined for each item. Diagnose and correct it.',language:'JavaScript'}
};
const promptFor:Record<string,(get:(id:string)=>string)=>string>={
 resume:g=>`Act as an expert ATS resume strategist. Compare the resume against the job description. Return match score with reasons, missing keywords, rewritten high-impact bullets, tailored summary and exact changes. Never invent experience.\n\nRESUME:\n${g('resume')}\n\nJOB DESCRIPTION:\n${g('jd')}\n\nTARGET ROLE:\n${g('role')}`,
 interview:g=>`Act as a senior interviewer. Create 8 role-specific questions, strong-answer guidance, 3 technical follow-ups, 3 behavioural questions, a tailored 30-second introduction and 5 pitfalls. Ground everything in the supplied evidence.\n\nJOB DESCRIPTION:\n${g('jd')}\n\nBACKGROUND:\n${g('bg')}\n\nSTAGE:\n${g('stage')}`,
 study:g=>`Act as a university tutor. Turn the supplied material into a revision pack: concise explanation, key concepts, formulas/rules where relevant, 12 flashcards, 10 exam questions with answers, common mistakes and a one-day revision plan. Do not invent facts.\n\nTOPIC:\n${g('topic')}\n\nMATERIAL:\n${g('notes')}\n\nDIFFICULTY:\n${g('difficulty')}`,
 content:g=>`Act as a sharp editor. Transform the brief into a publishable ${g('format')} with a strong hook, concrete value, natural voice, useful structure and clear ending. Avoid filler, fake statistics and empty hype. Provide 3 alternative hooks.\n\nIDEA:\n${g('brief')}\n\nAUDIENCE:\n${g('audience')}`,
 code:g=>`Act as a senior ${g('language')} engineer. Diagnose the supplied code and error. Return root cause, exact corrected code, explanation, tests and one prevention improvement. Do not rewrite unrelated code.\n\nCODE:\n${g('code')}\n\nERROR / EXPECTED BEHAVIOUR:\n${g('errorInfo')}\n\nLANGUAGE:\n${g('language')}`
};
function esc(s:unknown){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]!));}
function val(root:HTMLElement,id:string){return (root.querySelector<HTMLInputElement|HTMLTextAreaElement>(`#${id}`)?.value||'').trim()}
function fieldsHtml(flow:string){return workflows[flow].fields.map(([label,id,type,ph])=>type==='ta'?`<label for="${id}">${label}<textarea id="${id}" placeholder="${esc(ph)}"></textarea></label>`:`<label for="${id}">${label}<input id="${id}" placeholder="${esc(ph)}"></label>`).join('')}
function loadSample(root:HTMLElement,flow:string){Object.entries(samples[flow]).forEach(([id,v])=>{const el=root.querySelector<HTMLInputElement|HTMLTextAreaElement>(`#${id}`);if(el)el.value=v})}
function loginUrl(){return `/auth/?next=${encodeURIComponent(location.pathname+location.search+location.hash)}`}
async function invoke(provider:Provider,flow:string,prompt:string){if(!supabase)throw new Error('AI service is not configured on this deployment.');const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Sign in to use PARADOX AI Studio.');const res=await supabase.functions.invoke('ai-router',{headers:{Authorization:`Bearer ${token}`},body:{provider,task:`${flow} AI workflow`,prompt,system:'You are PARADOX AI Studio. Be accurate, concrete and transparent about uncertainty. Never invent credentials, sources, statistics or achievements. Structure useful output with clear headings.'}});if(res.error)throw new Error(res.error.message||'AI router request failed.');if(!res.data?.text)throw new Error(res.data?.error||'No AI output returned.');return res.data as {text:string;provider:string;latencyMs?:number}}
function init(){const root=document.querySelector<HTMLElement>('.studio');if(!root||root.dataset.controllerReady==='true')return;root.dataset.controllerReady='true';const fields=root.querySelector<HTMLElement>('#fields'),label=root.querySelector<HTMLElement>('#flowLabel'),title=root.querySelector<HTMLElement>('#flowTitle'),status=root.querySelector<HTMLElement>('#status'),result=root.querySelector<HTMLElement>('#result'),empty=root.querySelector<HTMLElement>('#resultEmpty'),error=root.querySelector<HTMLElement>('#error'),provider=root.querySelector<HTMLSelectElement>('#provider'),run=root.querySelector<HTMLButtonElement>('#run'),clear=root.querySelector<HTMLButtonElement>('#clear'),example=root.querySelector<HTMLButtonElement>('#example'),copy=root.querySelector<HTMLButtonElement>('#copy'),download=root.querySelector<HTMLButtonElement>('#download'),metaProvider=root.querySelector<HTMLElement>('.px-result-provider'),metaLatency=root.querySelector<HTMLElement>('.px-result-latency');let current=new URLSearchParams(location.search).get('workflow')||'resume';if(!workflows[current])current='resume';
 const render=(flow:string,reset=true)=>{current=flow;const w=workflows[flow];label!.textContent=w.label;title!.textContent=w.title;fields!.innerHTML=fieldsHtml(flow);root.querySelectorAll<HTMLButtonElement>('.flow').forEach(b=>b.classList.toggle('active',b.dataset.flow===flow));if(reset){result!.hidden=true;empty!.hidden=false;error!.hidden=true;status!.textContent='READY'}};
 root.querySelectorAll<HTMLButtonElement>('.flow').forEach(b=>b.addEventListener('click',()=>{render(b.dataset.flow||'resume');history.replaceState(null,'',`/ai-studio/?workflow=${encodeURIComponent(b.dataset.flow||'resume')}`)}));
 example?.addEventListener('click',()=>{loadSample(root,current);status!.textContent='EXAMPLE LOADED';});
 clear?.addEventListener('click',()=>render(current));
 copy?.addEventListener('click',async()=>{if(result!.hidden||!result!.textContent)return;try{await navigator.clipboard.writeText(result!.textContent);status!.textContent='COPIED'}catch{error!.textContent='Clipboard access is blocked. Select the result and copy manually.';error!.hidden=false}});
 download?.addEventListener('click',()=>{if(result!.hidden)return;const blob=new Blob([result!.textContent||''],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`paradox-${current}-result.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)});
 run?.addEventListener('click',async()=>{const ids=workflows[current].fields.map(x=>x[1]);if(ids.some(id=>!val(root,id))){error!.textContent='Complete all workflow inputs first, or use TRY EXAMPLE.';error!.hidden=false;return}let user:null|Awaited<ReturnType<typeof currentUser>>=null;try{user=await currentUser()}catch{error!.textContent='Authentication could not be checked. Please try again.';error!.hidden=false;return}if(!user){location.href=loginUrl();return}run.disabled=true;run.textContent='RUNNING…';status!.textContent='ROUTING AI';error!.hidden=true;result!.hidden=false;empty!.hidden=true;result!.textContent='Generating a structured result…';const started=performance.now();try{const data=await invoke((provider?.value||'auto') as Provider,current,promptFor[current](id=>val(root,id)));result!.textContent=data.text;status!.textContent=`DONE · ${String(data.provider||'AI').toUpperCase()}`;metaProvider!.textContent=String(data.provider||'AI').toUpperCase();metaLatency!.textContent=`${Math.max(1,Math.round(data.latencyMs||performance.now()-started))}MS · READY TO COPY`;window.gtag?.('event','ai_studio_run',{workflow:current,provider:data.provider})}catch(e){const m=e instanceof Error?e.message:'AI request failed.';if(/sign in/i.test(m)){location.href=loginUrl();return}result!.hidden=true;empty!.hidden=false;error!.textContent=m;error!.hidden=false;status!.textContent='ERROR'}finally{run.disabled=false;run.textContent='RUN AI ↗'}});
 render(current);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
export {};
