import { currentUser, supabase } from '../../lib/supabase.ts';

type Provider='auto'|'gemini'|'groq'|'cerebras'|'huggingface'|'ollama';
type Field=[string,string,'text'|'ta',string];
const workflows:Record<string,{label:string;title:string;description:string;fields:Field[]}>= {
 resume:{label:'RESUME TAILOR',title:'Make the application fit.',description:'Turn your actual experience into a role-specific, ATS-aware application without inventing anything.',fields:[['Your resume','resume','ta','Paste your resume here...'],['Job description','jd','ta','Paste the complete job description here...'],['Target role','role','text','Software Engineer']]},
 interview:{label:'INTERVIEW COACH',title:'Train against the actual role.',description:'Generate a focused interview plan from the job description and your real background.',fields:[['Job description','jd','ta','Paste the complete job description here...'],['Your background','bg','ta','Projects, experience, skills, education...'],['Interview stage','stage','text','Technical interview']]},
 study:{label:'STUDY ENGINE',title:'Turn notes into a revision system.',description:'Convert your source material into explanations, flashcards, questions and a practical revision plan.',fields:[['Topic or chapter','topic','text','DBMS — normalization'],['Notes / source material','notes','ta','Paste class notes, textbook text or source material...'],['Difficulty / exam','difficulty','text','University exam']]},
 content:{label:'CONTENT STUDIO',title:'Go from idea to publishable draft.',description:'Build useful, specific content with a strong hook and a format matched to the audience.',fields:[['Idea / brief','brief','ta','Describe what you want to publish...'],['Audience','audience','text','Developers and students'],['Format / platform','format','text','LinkedIn post']]}
};
const samples:Record<string,Record<string,string>>={
 resume:{resume:'Software engineering student. Built React + Node.js applications, REST APIs and PostgreSQL-backed projects.',jd:'Software Engineer\nBuild REST APIs, React interfaces, Git and database-backed products.',role:'Software Engineer'},
 interview:{jd:'Software Engineer\nReact, JavaScript, REST APIs, PostgreSQL, Git.',bg:'Computer Science student. Full-stack projects using React, Node.js, Express, PostgreSQL and MongoDB.',stage:'Technical interview'},
 study:{topic:'Database Management Systems — normalization',notes:'1NF requires atomic values. 2NF removes partial dependency. 3NF removes transitive dependency.',difficulty:'University exam'},
 content:{brief:'Launch announcement for a developer platform combining AI workflows and browser utilities.',audience:'Developers and students',format:'LinkedIn post'}
};
const promptFor:Record<string,(g:(id:string)=>string)=>string>={
 resume:g=>`Act as an expert ATS resume strategist. Analyze only the supplied evidence. Return: 1) match score with category-level reasoning, 2) matched keywords, 3) missing or weak keywords, 4) rewritten bullets using only real evidence, 5) tailored summary, 6) exact edits to make. Never invent experience, metrics, employers, education or skills.\n\nRESUME:\n${g('resume')}\n\nJOB DESCRIPTION:\n${g('jd')}\n\nTARGET ROLE:\n${g('role')}`,
 interview:g=>`Act as a senior interviewer for the supplied role. Return a structured preparation pack: 8 role-specific questions, what a strong answer should contain, 3 technical follow-ups, 3 behavioural questions, a 30-second introduction based only on the background, and 5 likely pitfalls. Do not invent experience.\n\nJOB DESCRIPTION:\n${g('jd')}\n\nBACKGROUND:\n${g('bg')}\n\nSTAGE:\n${g('stage')}`,
 study:g=>`Act as a university tutor. Transform the supplied material into a reliable revision pack: concise explanation, key concepts, formulas/rules only when supported, 12 flashcards, 10 exam questions with answers, common mistakes and a one-day revision plan. Clearly separate supplied facts from anything inferred. Do not fabricate source material.\n\nTOPIC:\n${g('topic')}\n\nMATERIAL:\n${g('notes')}\n\nDIFFICULTY:\n${g('difficulty')}`,
 content:g=>`Act as a sharp editor. Turn the supplied brief into a publishable ${g('format')}. Start with 3 hook options, then the final draft, then a short CTA. Match the supplied audience. Avoid filler, fake statistics, unsupported claims and generic AI language.\n\nIDEA:\n${g('brief')}\n\nAUDIENCE:\n${g('audience')}`
};
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const value=(root:HTMLElement,id:string)=>(root.querySelector<HTMLInputElement|HTMLTextAreaElement>(`#${id}`)?.value||'').trim();
const loginUrl=()=>`/auth/?next=${encodeURIComponent(location.pathname+location.search+location.hash)}`;
function renderFields(root:HTMLElement,flow:string){const fields=root.querySelector<HTMLElement>('#fields');if(!fields)return;fields.innerHTML=workflows[flow].fields.map(([label,id,type,ph])=>type==='ta'?`<label for="${id}"><span>${esc(label)}</span><textarea id="${id}" placeholder="${esc(ph)}"></textarea></label>`:`<label for="${id}"><span>${esc(label)}</span><input id="${id}" placeholder="${esc(ph)}" /></label>`).join('');}
function loadSample(root:HTMLElement,flow:string){Object.entries(samples[flow]).forEach(([id,v])=>{const el=root.querySelector<HTMLInputElement|HTMLTextAreaElement>(`#${id}`);if(el)el.value=v;});}
async function invoke(provider:Provider,flow:string,prompt:string){if(!supabase)throw new Error('AI service is not configured on this deployment.');const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Sign in to use PARADOX AI Studio.');const res=await supabase.functions.invoke('ai-router',{headers:{Authorization:`Bearer ${token}`},body:{provider,task:`${flow} AI workflow`,prompt,system:'You are PARADOX AI Studio. Be accurate, concrete and transparent about uncertainty. Never invent credentials, sources, statistics or achievements. Use clear headings and actionable output.'}});if(res.error)throw new Error(res.error.message||'AI router request failed.');if(!res.data?.text)throw new Error(res.data?.error||'No AI output returned.');return res.data as {text:string;provider:string;latencyMs?:number};}
function init(){const root=document.querySelector<HTMLElement>('.studio');if(!root||root.dataset.controllerReady==='true')return;root.dataset.controllerReady='true';const label=root.querySelector<HTMLElement>('#flowLabel'),title=root.querySelector<HTMLElement>('#flowTitle'),desc=root.querySelector<HTMLElement>('#flowDescription'),fields=root.querySelector<HTMLElement>('#fields'),status=root.querySelector<HTMLElement>('#status'),result=root.querySelector<HTMLElement>('#result'),empty=root.querySelector<HTMLElement>('#resultEmpty'),error=root.querySelector<HTMLElement>('#error'),provider=root.querySelector<HTMLSelectElement>('#provider'),run=root.querySelector<HTMLButtonElement>('#run'),example=root.querySelector<HTMLButtonElement>('#example'),clear=root.querySelector<HTMLButtonElement>('#clear'),copy=root.querySelector<HTMLButtonElement>('#copy'),download=root.querySelector<HTMLButtonElement>('#download'),metaProvider=root.querySelector<HTMLElement>('.px-result-provider'),metaLatency=root.querySelector<HTMLElement>('.px-result-latency');let current=new URLSearchParams(location.search).get('workflow')||'resume';if(!workflows[current])current='resume';
 const render=(flow:string,reset=true)=>{current=flow;const w=workflows[flow];if(label)label.textContent=w.label;if(title)title.textContent=w.title;if(desc)desc.textContent=w.description;renderFields(root,flow);root.querySelectorAll<HTMLButtonElement>('.flow').forEach(b=>{b.classList.toggle('active',b.dataset.flow===flow);b.setAttribute('aria-current',b.dataset.flow===flow?'page':'false');});if(reset){result!.hidden=true;empty!.hidden=false;error!.hidden=true;status!.textContent='READY';metaProvider!.textContent='AI';metaLatency!.textContent='READY';}};
 root.querySelectorAll<HTMLButtonElement>('.flow').forEach(b=>b.addEventListener('click',()=>{const flow=b.dataset.flow||'resume';render(flow);const u=new URL(location.href);u.searchParams.set('workflow',flow);u.searchParams.delete('section');u.searchParams.delete('tool');history.replaceState(null,'',u.pathname+u.search);}));
 example?.addEventListener('click',()=>{loadSample(root,current);status!.textContent='EXAMPLE LOADED';error!.hidden=true;});
 clear?.addEventListener('click',()=>render(current));
 copy?.addEventListener('click',async()=>{if(result!.hidden||!result!.textContent)return;try{await navigator.clipboard.writeText(result!.textContent);status!.textContent='COPIED'}catch{error!.textContent='Clipboard access is blocked. Select the result and copy manually.';error!.hidden=false;}});
 download?.addEventListener('click',()=>{if(result!.hidden)return;const blob=new Blob([result!.textContent||''],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`paradox-${current}-result.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800);});
 run?.addEventListener('click',async()=>{const ids=workflows[current].fields.map(x=>x[1]);if(ids.some(id=>!value(root,id))){error!.textContent='Complete every input first, or use TRY EXAMPLE.';error!.hidden=false;return;}let user=null;try{user=await currentUser();}catch{error!.textContent='Authentication could not be checked. Please try again.';error!.hidden=false;return;}if(!user){location.href=loginUrl();return;}run.disabled=true;run.textContent='RUNNING…';status!.textContent='ROUTING AI';error!.hidden=true;result!.hidden=false;empty!.hidden=true;result!.textContent='Generating structured output…';const started=performance.now();try{const data=await invoke((provider?.value||'auto') as Provider,current,promptFor[current](id=>value(root,id)));result!.textContent=data.text;status!.textContent=`DONE · ${String(data.provider||'AI').toUpperCase()}`;metaProvider!.textContent=String(data.provider||'AI').toUpperCase();metaLatency!.textContent=`${Math.max(1,Math.round(data.latencyMs||performance.now()-started))}MS`;window.gtag?.('event','ai_studio_run',{workflow:current,provider:data.provider});}catch(e){const m=e instanceof Error?e.message:'AI request failed.';if(/sign in/i.test(m)){location.href=loginUrl();return;}result!.hidden=true;empty!.hidden=false;error!.textContent=m;error!.hidden=false;status!.textContent='ERROR';}finally{run.disabled=false;run.textContent='RUN AI ↗';}});
 render(current);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
export {};
