import { supabase } from '../../lib/supabase.ts';
const startStudio=()=>{const rootEl=document.querySelector<HTMLElement>('#studioPage,.studio');if(!rootEl||rootEl.dataset.studioUiReady==='true')return;const root=rootEl;root.dataset.studioUiReady='true';document.documentElement.classList.add('studio-runtime');
const tabs=[...root.querySelectorAll<HTMLButtonElement>('[data-section-tab]')];const panels={workflows:root.querySelector<HTMLElement>('#studioWorkflows'),toolkit:root.querySelector<HTMLElement>('#studioToolkit'),radar:root.querySelector<HTMLElement>('#studioRadar')};
const setSection=(section:'workflows'|'toolkit'|'radar',writeUrl=true)=>{root.dataset.activeSection=section;tabs.forEach(tab=>{const active=tab.dataset.sectionTab===section;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));});Object.entries(panels).forEach(([key,panel])=>{if(panel)panel.hidden=key!==section;});if(writeUrl){const u=new URL(location.href);u.searchParams.delete('section');u.searchParams.delete('workflow');u.searchParams.delete('tool');if(section==='toolkit'){u.searchParams.set('section','toolkit');const active=root.querySelector<HTMLElement>('.studio-tool-select.active');if(active?.dataset.toolSelect)u.searchParams.set('tool',active.dataset.toolSelect);}else if(section==='radar')u.searchParams.set('section','radar');else u.searchParams.set('workflow',root.querySelector<HTMLElement>('.flow.active')?.dataset.flow||'resume');history.replaceState(null,'',u.pathname+u.search);}if(section!=='workflows'){const panel=panels[section];if(panel)requestAnimationFrame(()=>window.scrollTo({top:Math.max(0,panel.getBoundingClientRect().top+window.scrollY-96),behavior:'smooth'}));}if(section==='radar')void loadRadar(true);};
const chooseTool=(button:HTMLElement)=>{root.querySelectorAll<HTMLElement>('.studio-tool-select').forEach(item=>item.classList.toggle('active',item===button));const mode = button.dataset.toolMode || '';root.querySelectorAll<HTMLElement>('[data-studio-tool-instance]').forEach(instance => {instance.hidden = instance.dataset.studioToolInstance !== mode;});setSection('toolkit',false);window.dispatchEvent(new CustomEvent('paradox:ai-tool-change',{detail:{mode:button.dataset.toolMode||'',title:button.querySelector('span')?.childNodes[0]?.textContent?.trim()||'Developer Tool',intro:button.querySelector('small')?.textContent?.trim()||''}}));const u=new URL(location.href);u.searchParams.set('section','toolkit');if(button.dataset.toolSelect)u.searchParams.set('tool',button.dataset.toolSelect);history.replaceState(null,'',u.pathname+u.search);};
tabs.forEach(tab=>tab.addEventListener('click',()=>{const section=(tab.dataset.sectionTab||'workflows') as 'workflows'|'toolkit'|'radar';if(section==='toolkit'){const active=root.querySelector<HTMLElement>('.studio-tool-select.active')||root.querySelector<HTMLElement>('.studio-tool-select');if(active)chooseTool(active);else setSection('toolkit');}else setSection(section);}));
root.querySelectorAll<HTMLButtonElement>('.flow').forEach(button=>button.addEventListener('click',()=>{const flow=button.dataset.flow||'resume';root.querySelectorAll<HTMLElement>('.flow').forEach(item=>item.classList.toggle('active',item===button));setSection('workflows',false);const u=new URL(location.href);u.searchParams.set('workflow',flow);u.searchParams.delete('section');u.searchParams.delete('tool');history.replaceState(null,'',u.pathname+u.search);window.dispatchEvent(new CustomEvent('paradox:workflow-change',{detail:{flow}}));}));root.querySelectorAll<HTMLButtonElement>('.studio-tool-select').forEach(button=>button.addEventListener('click',()=>chooseTool(button)));
let radarLoaded=false;
async function loadRadar(force=false){
 if(radarLoaded&&!force)return;
 const models=root.querySelector<HTMLElement>('#radarModels'),github=root.querySelector<HTMLElement>('#radarGithub'),news=root.querySelector<HTMLElement>('#radarNews'),status=root.querySelector<HTMLElement>('#radarStatus'),refresh=root.querySelector<HTMLButtonElement>('#radarRefresh');
 if(!models||!github||!news||!status)return;
 status.textContent='FETCHING…'; if(refresh)refresh.disabled=true;
 const direct=async<T>(url:string):Promise<T>=>{const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),12000);try{const response=await fetch(url,{signal:controller.signal,cache:'no-store',headers:{Accept:'application/json'}});if(!response.ok)throw new Error(String(response.status));return await response.json() as T;}finally{window.clearTimeout(timer);}};
 const directResult=await Promise.allSettled([
   direct<unknown[]>('https://huggingface.co/api/models?sort=trending&direction=-1&limit=12'),
   direct<{items?:unknown[]}>('https://api.github.com/search/repositories?q=AI+OR+LLM&sort=stars&order=desc&per_page=12'),
   direct<{hits?:unknown[]}>('https://hn.algolia.com/api/v1/search?query=AI%20LLM&tags=story&hitsPerPage=12')
 ]);
 let proxy:{models?:unknown[];repositories?:unknown[];stories?:unknown[]}={};
 if(supabase){try{const {data,error}=await supabase.functions.invoke<{models?:unknown[];repositories?:unknown[];stories?:unknown[]}>('ai-radar',{body:{}});if(!error&&data)proxy=data;}catch{}}
 const directModels=directResult[0].status==='fulfilled'&&Array.isArray(directResult[0].value)?directResult[0].value:[];
 const directRepos=directResult[1].status==='fulfilled'?(directResult[1].value.items||[]):[];
 const directStories=directResult[2].status==='fulfilled'?(directResult[2].value.hits||[]):[];
 const rawModels=proxy.models?.length?proxy.models:directModels;
 const rawRepos=proxy.repositories?.length?proxy.repositories:directRepos;
 const rawStories=proxy.stories?.length?proxy.stories:directStories;
 const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
 const m=rawModels.map((x:unknown)=>{const v=x as Record<string,unknown>;return {id:String(v.id||v.modelId||v.name||'Model'),url:String(v.url||`https://huggingface.co/${v.id||v.modelId||''}`),downloads:Number(v.downloads||0),likes:Number(v.likes||0)};});
 const g=rawRepos.map((x:unknown)=>{const v=x as Record<string,unknown>;return {name:String(v.full_name||v.name||'Repository'),url:String(v.url||v.html_url||'#'),stars:Number(v.stars??v.stargazers_count??0),language:String(v.language||'AI project')};});
 const n=rawStories.map((x:unknown)=>{const v=x as Record<string,unknown>;return {title:String(v.title||'AI story'),url:String(v.url||'https://news.ycombinator.com/'),points:Number(v.points||0),comments:Number(v.comments??v.num_comments??0)};});
 models.innerHTML=m.length?m.map((x,index)=>`<a class="studio-radar-card" href="${esc(x.url)}" target="_blank" rel="noreferrer"><b>${String(index+1).padStart(2,'0')}</b><strong>${esc(x.id)}</strong><span>${x.downloads.toLocaleString()} downloads · ${x.likes.toLocaleString()} likes</span></a>`).join(''):'<div class="radar-empty-state"><strong>MODELS FEED OFFLINE</strong><span>Both model feeds failed. Retry in a moment.</span></div>';
 github.innerHTML=g.length?g.map((x,index)=>`<a class="studio-radar-card" href="${esc(x.url)}" target="_blank" rel="noreferrer"><b>${String(index+1).padStart(2,'0')}</b><strong>${esc(x.name)}</strong><span>★ ${x.stars.toLocaleString()} · ${esc(x.language)}</span></a>`).join(''):'<div class="radar-empty-state"><strong>GITHUB FEED OFFLINE</strong><span>GitHub did not return data.</span></div>';
 news.innerHTML=n.length?n.map((x,index)=>`<a class="studio-radar-card" href="${esc(x.url)}" target="_blank" rel="noreferrer"><b>${String(index+1).padStart(2,'0')}</b><strong>${esc(x.title)}</strong><span>${x.points} points · ${x.comments} comments</span></a>`).join(''):'<div class="radar-empty-state"><strong>AI STORIES OFFLINE</strong><span>Hacker News did not return data.</span></div>';
 status.textContent=`${[m,g,n].filter(x=>x.length).length}/3 LIVE`; radarLoaded=true; if(refresh)refresh.disabled=false;
}
root.querySelector<HTMLButtonElement>('#radarRefresh')?.addEventListener('click',()=>void loadRadar(true));
const params=new URLSearchParams(location.search);const requested=params.get('section');if(requested==='radar')setSection('radar',false);else if(requested==='toolkit'){const slug=params.get('tool');const match=slug?root.querySelector<HTMLElement>(`.studio-tool-select[data-tool-select="${CSS.escape(slug)}"]`):root.querySelector<HTMLElement>('.studio-tool-select');if(match)chooseTool(match);else setSection('toolkit',false);}else setSection('workflows',false);};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startStudio,{once:true});else startStudio();
export {};